### PR TITLE
Re-position Success Criteria on front page

### PR DESCRIPTION
**Pull request by AramZS**
The Success Criteria document has been much debated and disputed. At some point it became the core document in a discussion around a different group and procedures elsewhere in the W3C. To avoid confusion, I propose we remove it from the front readme. We can retain the document for future reference and discussion, however, at this time I think we've moved on from it and it no longer fully represents the context of what this group aims to do.

### CODE REVIEW

**Comment by jwrosewell** [comment]
@AramZS  thank you for calling attention to the Success Criteria documents a large number of us wrote last year to help us better evaluate alternative proposed specifications to improve web advertising. 

As we’ve seen in the past few weeks, there are strong perspectives from various stakeholders as to how well their interests are supported by particular specifications discussed in our group in addition to how well specifications meet specific needs of users and supporting their important privacy rights. 

Your note suggests that this document ought to be moved to the new interest group that was proposed to ensure W3C specifications ensure they do not review potential impacts to the decentralized architecture of the web. This same concern was recently called out by the [TAG review of the First Party Sets](https://github.com/w3ctag/design-reviews/blob/main/reviews/first_party_sets_feedback.md) proposal that they believe “only benefits powerful, large entities that control both an implementation and services.”

The Decentralization Interest Group (DIG) charter proposal is still in draft form. Current work on W3C vision and values will hopefully negate the need for such a group. If that becomes the case, I will advocate for the Success Criteria and related Questionnaire to become official W3C documents that implementers may use to evaluate any proposal they present to any forum within the W3C. I would do this via the Advisory Committee.

Given this is still some way off, and the document was specifically drafted to help our business group evaluate rival specifications, I believe for now the best home for the document is our IWA BG. 

I think it would be useful for us to revisit this document and update it in light of the TAG review of First Party Sets, which they felt given the centralized control the specification gave browser implementers, without appropriate governance to protect people’s choices called “the efficacy of the "Privacy Sandbox" initiative is thrown into question.” 

Had we evaluated that proposals via the Success Criteria we would have been able to save hundreds of thousands of people hours of effort within this Business Group, discussing, evaluating, commenting, counter proposing, experimenting and debating. We would be a lot closer to a web that will improve advertising and achieving the mission of the group.

For all these reasons I would like to see greater emphasis placed on these documents. Given the Success Criteria and related Questionnaire received far more multi-party endorsement than many other documents in our repository, I suggest we keep these on the group’s home page. 

I do think there is a more general need to adopt the labelling applied to the Success Criteria documents across this repository to make it clear the document is not official in anyway. That however is a matter for the chair and editors of the respective documents.

**Comment by AramZS** [comment]
I think that we have not evaluated proposals via the Success Criteria. There is not a general agreement to evaluate proposals via the Success Criteria and the current week to week running of the group does not access the Success Criteria. The TAG review represents a specific process which is not related to the function of this group and has different concerns. The DIG group may one day take up this type of thinking but that is a separate group and *notably* not a business group. 

While I understand that you, individually, would like to use this success criteria, there has been no use of this document by the group and that means that in-action and in reality the success criteria has been rejected by this group. Our earlier attempt to adopt it sent us into a sequence of long pointless meetings that pulled us away from what most voices agreed was the core purpose of the group.

I have no objections to preserving the presence of the document. It is an interesting historical document. But your inability to engage on it in the context of pull request process (moving feedback to word document comments) is frustrating. Putting aside process for feedback, the fact of the matter is that it does not represent the actual state of this group. Including it on the front readme page as a document reviewed by potential new members is misleading. If you would like to bring back your attempt to have this group formally adopt this in some way, that is a different matter. Though I think that this is the wrong group for such a document and does not describe a process or success criteria that makes sense for the processes of this group. Whatever the case, as it currently stands it has not been adopted by the group. Retaining it as a product of this group on the Readme, when it does not represent an agreement or a practice that is currently in action, is confusing to new and potential members, as well as any outside entities who might wish to report on this group's action. 

Please note, I have no interest in erasing the document. I think it is a viewpoint that makes a useful reference. But I think it's placement in the readme doesn't make sense. As you say:

> Had we evaluated that proposals 

So we both agree that this document is not currently in use by this group. Portraying it as currently in use is misleading and should be fixed. If you would like to propose a more accurate re-titling of the document or its placement on the Readme that might be a way to accomplish the same goal.

**Comment by joshuakoran** [comment]
Hi @AramZS,
You raise (at least) three good points:

1. The document ought to be updated like other documents in our group via pull requests, rather than suggested edits in some other system. 
2. Our group is not aligned on what success criteria we are trying to meet when attempting to “improve” web advertising.
3. Should a different W3C group write the criteria the Improving Web Advertising should use to evaluate the relative merits of the various proposals we have been discussing for over a year. 

Let me address the second substantive point, which I would paraphrase as “Should we try to write down the reasons we think a given proposal is improving web advertising, as well as the tradeoffs such a proposal is advocating?” 

Personally, I think we would save a lot of time if proposals authors would write down what tradeoffs they are recommending the ecosystem make, and what foreseeable impact that would have on each group of stakeholders.  

The use cases you’ve mentioned are an important part of this process. However, I feel there are many interests not captured in the current use cases, that are captured in the success criteria document (specifically the interests of society, in addition to those of individual end users, publishers, marketers and browser implementors). 

I think we agree that the document captures many important viewpoints from internet stakeholders, including those not directly participating in our weekly meetings. I think we also agree that different stakeholders are advocating for different tradeoffs in the policy “tussles;” for example limiting only certain sized organizations’ ability to use people’s content consumption over time to help operate their businesses. 

Regarding the third point, had the Decentralization Interest Group been established, that could have been a forum to work on improving this document so that issues that TAG recently found with First Party Sets proposal, [disproportionately benefiting larger players](https://github.com/w3ctag/design-reviews/blob/main/reviews/first_party_sets_feedback.md), could have been caught far earlier in the process.

Given many proposals in our business group that have had far fewer organizations endorse them relative to this one, I would recommend we keep the document in the main repository.

However, if there are specific recommendations to improve the document, such as incorporating the success metrics outlined by Criteo’s Teetar, perhaps that would be useful to ensure we can all better understand the benefits and tradeoffs recommended by specific proposals.

**Comment by AramZS** [comment]
I agree that the document should remain in the repository @joshuakoran and have no objection to it remaining in place as it is. The core objection I have is it's placement in the README. It is, at best, a **proposed** success criteria, and I would argue that not only does it fail to represent a common opinion of stakeholders in this group, it does not even recognize a common understanding of what would be in the best interests of society--to the extent that such a thing is in the domain of this group.

I will note here once more these two points and drop the topic: 

1. To what extent the DIG proposal has or could be established and to what ends is outside the context of this group. 

2. The TAG review, which I would argue is fundamentally opposed to some of the stances in the Success Criteria document, is also not particularly a driving feature of this group. We do not do those reviews, we are not party to the process of writing these reviews (beyond being members of the W3C), and the reviews are not binding on W3C contributors. They are--as stated--reviews of the technical proposals that participants are expected to read and work with in good faith. At best they are a blocker for proposals being formally marked as adopted and final by other W3C groups. In any case, none of that is particularly contextually associated with the work of this group. At this time we have not taken up the task of approving, endorsing or even forming formal group reviews of any proposals. Nor have we shown the unified point of view that would presumably be required to do so. Nor are we required to have a unified point of view as a Business Group! At no point have we stated--as a unified group--opposition or approval to any particular proposal. I am not a W3C expert, but I do not think it is within the mandate of a Business Group to even do those activities. 

In an attempt to put aside and drop the question of the mechanics of what this group is, does, or could functionally do within the W3C, which is **significantly** beyond the reach of this PR, I will simply note [the founding document of the group](https://www.w3.org/community/web-adv/2017/12/21/improving-web-advertising-by-changing-the-web/) states:

> It will aim at identifying key areas where the Open Web Platform can be changed, and at starting Working Groups or liaising with existing Working Groups as needed.

I do not see approving or disapproving proposals as within that work description. Now if you would like to spin off a Working Group around the issues in the Success Criteria, I think the conversation around DIG is presumably the place where that is happening. 

> Personally, I think we would save a lot of time if proposals authors would write down what tradeoffs they are recommending the ecosystem make, and what foreseeable impact that would have on each group of stakeholders.

I think that is a good idea, and I think that part of the group's purpose is acknowledging that no single proposal author can fully do that, nor can any single group member and to collect opinions on those very issues. 

> However, I feel there are many interests not captured in the current use cases, that are captured in the success criteria document (specifically the interests of society, in addition to those of individual end users, publishers, marketers and browser implementors).

I am not sure I agree that is the case. However, we now have a clear methodology for handling that question that I think would be a better way to handle those questions or potential interests. They should be identified one at a time, added as per-use-case PRs, and added to the document that is collecting use cases. If you feel there are use cases that are not represented in the specific document that represents use cases, the best way I think to handle that is to add it to that use case document. That specific document is in a format and layout that makes it easy for proposers to reference it and for CGs, WGs and other participants to interact and review. 

The Success Criteria document is not in an easy format to reference or review. It does not cleanly map to use cases, which are a valuable output of this group and a primary point of interaction between our group, proposals, and other groups. To make claims for "the interests of society" is very very esoteric and identifying what exactly individuals think are in the interests of society and how that can map to any technical proposal is exactly how a discussion around a use case can turn whatever concern is theoretically being represented into something actionable for discussion. 

To the address the following:

> “Should we try to write down the reasons we think a given proposal is improving web advertising, as well as the tradeoffs such a proposal is advocating?”

We absolutely should. Thus far the most successful way we have done so is by breaking down the use case(s) it is impacting, how we perceive that impact, and to what extent it will fulfill or block that use case. We have, thus far, established a clear, functioning, pattern to do so that is presumably what you would want to do with the use cases you think are not currently covered in the use case document: 

Step one is identifying that use case in an issue. 

Step two is identifying the details of that use case be it 'assure fraud isn't happening' or 'preserve democracy' (if you wish, but one of those use cases has a clear input and output and the other would require a great deal more explanation than is in the Success Criteria document and a lot of discussion to apply as a relevant context). And then adding it to the use case document via a PR.

Step three is requesting an overview of the proposals that concern the use case to this group. Something we have had great success in doing and seems to have had good results in bettering all members' understanding of the proposals. 

Step four is taking your understanding of the tradeoffs and putting them in a Github issue on the proposal itself. 

Since this group does not create unified formal reviews on proposals and is not designed to, using the information you get through participation and the clear defined use cases we can establish, and then taking your individual or organizational viewpoint to the proposal has thus far been the flow. I don't see that changing. 

Once again, I'll repeat my note from my previous comment:

I think that you and I both agree that this group does not currently use this document as part of its process. Since all three of us on this thread agree that the document is not currently used as a Success Criteria for the operation of this group or its output, removing it from the misleading position in the README that implies it is seems to be a clear next step. 

Beyond that, further work on the document is something that clearly more than one person is interested in, and can move forward within this repository. If we wish to *actually* adopt it as part of this group's methodology then I think that would require a reworking of the regular meetings and methods of this group and a formal adoption by the group, along with some sort of conversation with the core leadership of the W3C to assure that this makes sense within their structure. From what I've seen, their feedback thus far has been that it describes the role of something that isn't a BG, but that is a matter for a version of this group that takes up the Success Criteria. This group has--in actual practice--not done that. We seem to all agree on that. If that's the case, it should either be removed from the README as I suggest or edited to make it clear that it is a "proposal" and not a current in-use document. 

The only questions that are in-context for this PR are the following:

### Does this group currently use the Success Criteria in practice? 

We all agree it does not. 

### Has it indicated a common understanding or intent to do so? 

I have not seen such an agreement or adoption or approval of such adoption as within the purview of this group by the W3C.

Does anyone disagree? 

I'm willing to take counter proposals for how to present this document on the README. Otherwise, I think the next step is removing it from the README, but retaining the document in this repo for further discussion if we wish to have it.

**Comment by AramZS** [comment]
(An additional thought on post-removal steps:

If you feel that a use case is the wrong structure for your concerns, then we should set up a document in a similar format to our use cases in which individuals can list their context and what they consider as success criteria and how proposals mesh with that criteria. So something like this:


------------------

Title: Stated Success Criteria

Subtitle: Ad network Stated Success Criteria 
| Use-case | Chrome | Safari | Community Proposals |
|----------|--------|--------|---------------------|
| [A Specific Criteria you as an ad network consider a requirement for a successful proposal] - with a link to the issue or document describing the criteria in detail | The associated Chrome Proposal and how it matches your criteria | etc | etc etc |

------------------

After we remove this document from the readme we could work on establishing such a document which has a clear outline of what you consider success criteria from your particular perspective if you think that is needed.

But I think the use case document is likely the best place for these concerns)

**Comment by jwrosewell** [comment]
@joshuakoran states, and @AramZS agrees.

> Personally, I think we would save a lot of time if proposals authors would write down what tradeoffs they are recommending the ecosystem make, and what foreseeable impact that would have on each group of stakeholders.

It appears all the commenters on this pull request agree that a method is needed to document trade-offs and evaluate proposals. Until we have consensus on this then we cannot more forward. 

This is where we should focus our energies.

A significant issue the W3C faces is that people are the primary constituent of the web, and everyone claims to speak on their behalf. I was recently pointed at a 2014 report titled "[The Promise and Shortcomings of Privacy Multistakeholder Policymaking: A Case Study]( https://core.ac.uk/download/pdf/234109764.pdf)" which covers the W3C and DNT. It is worth reading when considering how we make meaningful progress. I particularly like these quotes.

> Whom are Working Group participants representing? For example, did Mayer, the Stanford PhD student and privacy advocate who joined the Working Group as an “invited expert,” represent 2.5 billion Internet users or just himself? Or perhaps something in between, such as all Internet users who live in Palo Alto and own a Mac?

> Working Group discussions ran rampant without a backstop, as even the chairs were unauthorized to crystalize the discussion into a compromise text.

> While Wiley argued that hashing unique identifiers would be sufficient to separate data from real world identities, Felten and Mayer believed that as long as such pseudonymized data could be re-identified, it must be viewed as personal.

The report concludes.

> However, to avoid evident pitfalls, multistakeholder processes should: 1) be structured around manifest and achievable goals; 2) set forth clear procedures for voting, decision-making, and consensus; 3) devise rational, fair rules of representation, taking into account the relative costs and benefits and access to resources that various stakeholders have; 4) seek to coalesce around straw man documents as early as possible in the process; 5) empower a chair or editor to express decisions in writing; and 6) optimally operate under a backstop of formal rulemaking, which will reduce any incentive to stall.

The use cases document is important, but does nothing to identify consequences beyond the specific use case.

@AramZS thank you for raising these points which should be addressed to try and move this discussion forward.

> It is, at best, a proposed success criteria

All documents in this repository are proposals.

> and I would argue that not only does it fail to represent a common opinion of stakeholders in this group, it does not even recognize a common understanding of what would be in the best interests of society--to the extent that such a thing is in the domain of this group

How do you know it does not represent a common opinion of stakeholders?

Like other documents in the repository the two documents being referred to are questions for consideration with some background to aid the reader.

The document was written with knowledge of the interim report and then [final report]( https://assets.publishing.service.gov.uk/media/5fa557668fa8f5788db46efc/Final_report_Digital_ALT_TEXT.pdf) from the UK’s Competition and Market Authority. This document represents the views of the society I live in and was written in collaboration with the equivalent competition authority in Australia who have produced a similar [report in March 2021]( https://www.accc.gov.au/publications/serial-publications/digital-platform-services-inquiry-2020-2025/digital-platform-services-inquiry-march-2021-interim-report). These provide valuable input.

> removing it from the misleading position in the README that implies it is part of the operation of this group seems to be a clear next step

I use the document regularly. If the main issue of this pull request is to perform a general house keeping exercise on the index of the repository used by the group, then we should discuss that at a future meeting. 

I would prefer to hear from the Partnership for Responsible Addressable Media (PRAM), the European Publishers Council (EPC), and advertising technology companies who are here to represent the interests of their customers who do not attend themselves, before changing anything.

> Now if you would like to spin off a Working Group around the issues in the Success Criteria, I think the conversation around DIG is presumably the place where that is happening.

Some of us who worked on these documents and then progressed the DIG charter are steering the [vision and values]( https://github.com/WebStandardsFuture/Vision/) of the W3C to address the concerns we have around centralization, open markets and competition. Not enough of members of this group are involved in that debate. I would urge participants in IWA BG who are concerned about markets, decentralization and competition to provide input into the vision and values work. Perhaps there will be no need for a group such as DIG and these documents can become W3C documents alongside ethical web principles and security and privacy documents, without the need for an interest group.

> The TAG review, which I would argue is fundamentally opposed to some of the stances in the Success Criteria document, is also not particularly a driving feature of this group. We do not do those reviews, we are not party to the process of writing these reviews (beyond being members of the W3C), and the reviews are not binding on W3C contributors. 

The TAG must upgrade the architectural pillars of the web to reflect the reality of data controller and processor relationships and impacts on competition. The FPS TAG report could be the start of that process. It obliquely recognises these issues. Supporters of first party sets and decentralized web seem to be able to agree on this.

This group does intend to create standards in the future. These standards will be subject to review by TAG at some point. It is better to be forewarned.

> The Success Criteria document is not in an easy format to reference or review.

The document has been modelled on other W3C documents that are regularly used, specifically the [security and privacy questionnaire](https://www.w3.org/TR/security-privacy-questionnaire/). The criteria reference the security and privacy questionnaire.

Let’s hear from more stakeholders before doing anything further with this PR.

**Comment by joshuakoran** [comment]
Hi Wendy,

I agree with Basile's comment today that a group that is proposing to "improve" web advertising ought to document the metrics/measures to know the changes are actually improving web advertising.

I agree we can relabel the document to be clearer that it is not a final version, but rather a draft that would benefit from those with different opinions enhancing the document to better capture their perspectives.

Best,
Joshua


[https://mailsig.zetaglobal.com/zetasig.png]<https://zetaglobal.com/>

Joshua Koran
Head of Zeta Innovation Labs

e. ***@***.******@***.***> m.?(650) 274-1041

a. San Francisco, CA
www.zetaglobal.com<https://www.zetaglobal.com>
[https://mailsig.zetaglobal.com/linkedin.png]<https://www.linkedin.com/company/zetaglobal>     [https://mailsig.zetaglobal.com/instagram.png] <https://www.instagram.com/zetaglobal>      [https://mailsig.zetaglobal.com/facebook.png] <https://www.facebook.com/zetaglobal>      [https://mailsig.zetaglobal.com/twitter.png] <https://www.twitter.com/zetaglobal>


This message contains information which may be confidential and privileged. You may not use, copy, or disclose to anyone, the message, or any information contained in this message for purposes not intended by the sender. If you have received the message in error, please advise the sender by reply e-mail, and delete the message .

**Comment by AramZS** [comment]
Edited this PR to move Success Criteria to Proposed Success Criteria under proposals, as per discussion in the group.

**Review by wseltzer — APPROVED** [review]

**Pull request merged**
